### ISSUE TITLE
autogeneration of encryption key in answerfile.txt does not work

### ISSUE THREAD

**Issue by cornexo** [lnxjedi/gopherbot#182]
When ` ANS_ENCRYPTION_KEY="g"` is configured in answerfile.txt gopherbot hangs on first run.

```$ tail robot.log
2020/03/29 16:47:10 Info: Initializing plugin: knock
2020/03/29 16:47:10 Info: Initializing plugin: admin
2020/03/29 16:47:10 Info: Initializing plugin: autosetup
2020/03/29 16:47:10 Info: Initializing plugin: citools
2020/03/29 16:47:10 Info: Initializing plugin: ssh-admin
2020/03/29 16:47:10 Info: Robot is initialized and running
2020/03/29 16:49:02 Info: Exiting on signal: interrupt
2020/03/29 16:49:02 Info: Stop called with 1 pipelines running
2020/03/29 16:49:02 Error: Waiting on external command '/opt/gopherbot/plugins/autosetup.sh': signal: interrupt
2020/03/29 16:49:02 Info: Stopping signal handler```

**Comment by parsley42** [comment]
Thanks for the report.

I was unable to reproduce this issue with current "master":
```
davidparsley@penguin:~/git/iclu$ grep "^  ANS_ENC" answerfile.txt 
  ANS_ENCRYPTION_KEY=g
davidparsley@penguin:~/git/iclu$ grep ENC .env 
GOPHER_ENCRYPTION_KEY=MFZu6uIdwPZemvRbfA37QUc3N1thxvFo
```
The expected behavior is for the `autosetup` plugin to not be enabled at all on the first run; from the default robot.yaml:
```
{{ if env "GOPHER_UNCONFIGURED" }}
  {{- if eq $proto "terminal" }}
  "welcome":
    Description: The welcome plugin provides a greeting when unconfigured
    Path: plugins/welcome.sh
  {{- end }}
  "autosetup":
    Description: Setup plugin for creating a new robot from an answerfile
...
{{ end }}
```
(start code only sets GOPHER_UNCONFIGURED when there is no custom/conf/robot.yaml)

I pushed a small change to master to improve logging and preserve content from `robot.log`. To aid in troubleshooting, could you run initially (answerfile only) with `GOPHER_LOGLEVEL=debug /path/to/gopherbot`, then on first run with `GOPHER_LOGLEVEL=debug ./gopherbot | tee -a robot.log`.

That should capture a pretty complete log of the install. Apparently it's possible to attach `*.log` files to Github issues: https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests. If you wouldn't mind generating and attaching the log file, I'll see if I can determine where it got off the rails. If you're concerned about potentially sensitive content (there shouldn't be any), feel free to email the log to parsley@linuxjedi.org.

**Comment by parsley42** [comment]
Per @cornexo , not reproducible with current code.
