### ISSUE TITLE
Bot can not read other bots messages

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#2]
I have a one specific channel for jira slackbot. It posts jira events to its channel. On the other hand my own bot listens jira channels messages and does some action. That does not work currently with gopherbot. So i debugged the code and realize that on the below line:
https://github.com/uva-its/gopherbot/blob/master/connectors/slack/util.go#L160
`msg.Msg.Text` is empty when its a bot message.  And userID is also empty.  So if a message comes from another bot, gopherbot should extract text from `msg.Attachments[0].Fallback`. What do you think about this ?

**Comment by parsley42** [comment]
I'd definitely like gopherbot to be able to "hear" messages from other integrations. I think there are two issues here:
- Instead of sending "user":"U<something>", slack sends "bot_id":"B<something>"; the connector needs to maintain a map between the Slack internal "B<something>" bot_id and a human-readable name to pass in the "user" parameter. This should probably get a prefix like "bot:", e.g. "bot:jira"
- Our "AWS notifier" integration sends it's text in msg.Msg.Text, so bot messages do sometimes send text; however, if text is empty, it seems sane to use the fallback instead

I'll see if I can make a first pass at this, as it's functionality I'm going to want at some point.

**Comment by parsley42** [comment]
Ok, the robot should hear other bots messages now. Note that bot names aren't guaranteed unique, (but I believe the internal BFOOBARBAZ ID _is_), so the value for User is "bot:<name>:BFOOBARBAZ". I tested this with our "AWS Notifier" integration, and the bot was able to hear updates. Also, I put in a simple check for msg.Msg.Text == "", in which case it checks msg.Attachments[0].Fallback.

**Comment by parsley42** [comment]
Also - I'm guessing you can just pull the updated repo and build the dist archive with './mkdist.sh'. Note that the naming of the script plugin libraries has changed to gopherbot_v1.<ext> to allow for future versioning, so you'll need to update your plugins if you're using bash/python/ruby.

**Comment by pasali** [comment]
It is working now. Thanks for the quick solution.
