### ISSUE TITLE
Provide a way to access Slack userId

### ISSUE THREAD

**Issue by pasali** [lnxjedi/gopherbot#6]
It would be very nice to get userId information from bot.
Ex: r.userId or maybe r.User.Id

**Comment by parsley42** [comment]
Do you mean the Slack internal user ID? (e.g. U12345678)

**Comment by pasali** [comment]
Yes.

**Comment by parsley42** [comment]
Ok, that shouldn't be hard; the preferred way would be to add a new attribute that can be retrieved with Get*Attribute, so e.g. : `id = r.GetSenderAttribute("internalID")`. I've added it to my Trello board, but not sure when I'll get around to it.

**Comment by parsley42** [comment]
Incidentally, do you mind sharing the use case?

**Comment by pasali** [comment]
I need to pass slack user information to  another service. So that service will be able to pass some message to slack when it needs to. Ex: Slack -> MyBot -> CircleCI then CircleCI -> Slack.

**Comment by parsley42** [comment]
Ah, gotcha - an integration thing, nifty.

Ok, it ended up being a 2-line addition to connectors/slack/connectorMethods.go. I haven't actually tested it, since it's Obviously Correct. Just use r.GetSenderAttribute("internalID"), or GetUserAttribute(<user>,"internalID").

Note, though, that I've only added this to the 1.0.0-test release, which has a breaking change if you've used the WaitForReply* methods, or, less likely, elevation functionality. Let me know if you need a back-ported 0.9.1 release.

**Comment by pasali** [comment]
i will give a try and let you know, thanks for quick solution

**Comment by pasali** [comment]
sorry for the late feedback it works fine :)
